name: Package A CI

on:
  push:
    branches: # 限制触发的分支
      - main
    # tags:
    #   - 'v*'
    paths: # 限制触发的文件
      - 'vite-plugin-svelte-imgsrc2import/**'
  pull_request:
    branches:
      - main
    paths:
      - 'vite-plugin-svelte-imgsrc2import/**'
  workflow_dispatch:  # 支持手动触发工作流
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'

# 如果你要分别对 代码提交 和 tag 创建 做不同的处理,可以这样写
# jobs:
#   build:
#     if: startsWith(github.ref, 'refs/heads/')
#     ...

#   release:
#     if: startsWith(github.ref, 'refs/tags/')
#     ...
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 安装依赖
      - name: Install dependencies for Package A
        working-directory: vite-plugin-svelte-imgsrc2import
        run: npm ci

      # 打包
      - name: Build Package A
        working-directory: vite-plugin-svelte-imgsrc2import
        run: npm run build
